language: node_js
sudo: required
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
node_js: stable
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
dist: trusty
env:
  global:
  - secure: nvHOs+ICIXb3MPQm19Jz3nTMpjiGjZMjvDd9HLNuT8lBVC71QSgh6ih+7KV0sCgM55qxXjbwNRHhzfMqu6wnUVQDG6wK+ZC1OmqIlyvydtQbtair7mIvhglxEmGn83lsBndcutx7NxuD9PVF1fpcVXK6FyIJYXxpx2YFxoSGcGdo44SvKPqL/YGq3WUfuMqoEhdqVC+5OKYseTZf3ZHaMcMKLeziOhpnjfmgri9nnYGuP0FhSapq6+NtEOgacxwrYfFiD7Kg+DvUWtUP82zv/Xb26tNxlm6bhW+5Fugrgd41TCAhir9ent87IqV8kR1WWiOS0YxL4Is944c/G0WDVD8aLpfDMuVto0VHaAXpgdSfN9PFGtuR+jTVQoBujgcKH/Ke4PW+Nsjf+RLL/vhkEElndp7XgIuFPsn3lwDk+vHDxjOPbWR/ngYhQNbW/Ei/EtSjMErEbweaTrUN8HlQIkYs27MxuntFrClAKsloil8Ues9ZCjT7fWAMaOCs+hMu9PWeznp7HysWp+X0kPYV9IiTJvUmgXPTGlXbU9oK0HnHKgNNx/CyQ596U1t0DMpmjrcG5YLweE6EHCfnRBj/SGIgiFDqWfoW5jwFNrehspm/YTjNsDIt7L/8h91O6X3biHOHmdis8XGDG1zrdF8pGzVS2YjZ56t/485VjonhuiI=
  - secure: FPfH+LnHkP5C3TgFp7hfxNMNPlip4DxuLMeWjSIPWK/5WwguR3+hFtZG3d1ozW8l2mKB1iO2a/UVBGf7S/BaMwNGuHs+wVLtO8NuL4g5ks69vKnXS9g90+YTb2vkZbceK1NxdMFjnB/gDn5dXc3uvyvicAIMhu5tzti3ADkGRl9+Mu5xFuOILmr+CkqYdADPN0yedTu+j9XjTvf1aBzC+heQtxX/pnPsC2HO9atcW3WKJgeKvBKB4rrV+kuadhpH+XKh/277NUsD9N4yt+eV5gMRhfxGgZoQXvAJHyVSYfqqGOUHuEaWgy7p91V6PrHkcWVa4xnWetOKp5mDC80neZc2D582SGg6xTvgEIgVAXoLmV0QfMoyN67MCbpKm6mfCYm8Fy1BA7Dff4Ddb/LMIKpjXpwsy2/rvVlI1lJOOycsPT9d+YDFaAkHO+5fX7v5+80XFexbdnp8JfAjjvmh0KNqcsTRhbNqW0YS1rrV9kzUHQLmshRaiXyTDNi8yatEWVWpOgz+WtcXRiVVkxlqMJomQg2bygb6elwhPxS1GAg8EMt6aTPTSN5+jgCcsYad4qWoquC8JERawp9uwRRnvgAShQc1DBJaWS0ZthJhvDU3tOd/tcw//gPWIhTDlEmIERaf6VIrFp/FSxTy3EAeJcahq36NgKAlVs1WJuPzLs0=
